# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Administrator'), ('User', 'User')], default='User', max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat',
            field=models.CharField(max_length=128, verbose_name='Wechat'),
        ),
    ]
